### ISSUE TITLE
Migrate to disnake

### ISSUE THREAD

**Issue by neanias** [Roxerg/collagerator#20]
[`discord.py` has been archived and marked dead](https://github.com/Rapptz/discord.py#the-future-of-discordpy). There's [a fork of `discord.py` called `disnake`](https://github.com/EQUENOS/disnake) which supports new slash commands and seems to have all the same features that `discord.py` provided. Given `disnake` is maintained and under active development, it would probably be wise to migrate to it.

**Comment by Roxerg** [comment]
Currently working on this
